### ISSUE TITLE
Clinical trials

### ISSUE THREAD

**Issue by agitter** [kjappelbaum/awesome-chemistry-datasets#35]
https://clinicaltrials.gov/ has free text descriptions of clinical trials. It should be possible to filter for trials that involve drug interventions, are completed with results, etc. to enrich the corpus to be more relevant or avoid incorrect associations like ivermectin and COVID-19 for which many trials were run but treatment is ineffective.

One example trial of many https://clinicaltrials.gov/ct2/show/NCT00108524

This site is US-based, and the same idea applies for https://www.clinicaltrialsregister.eu/ and other regions.

**Comment by kjappelbaum** [comment]
Thanks also for this one!
