### ISSUE TITLE
Add NLMChem

### ISSUE THREAD

**Issue by apoorvasrinivasan26** [kjappelbaum/awesome-chemistry-datasets#56]
Found [NLMChem](https://ftp.ncbi.nlm.nih.gov/pub/lu/NLMChem/), a manually annotated full-text resource on chemicals in the biomedical literature. It contains 150 full-text journal articles selected both to be rich in chemical mentions and for articles where human annotation was expected to be most valuable. However, I saw NLM literature archive already on the list but wasn't sure if it included this dataset

**Comment by kjappelbaum** [comment]
Thanks, added it as a note to the NLM literature archive!
